server:
  port: ${SERVER_PORT:8093}

# Logging configuration
logging:
  level:
    com.plazoleta.messaging_microservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# External services configuration
external:
  twilio:
    account-sid: ${TWILIO_ACCOUNT_SID:test_account_sid}
    auth-token: ${TWILIO_AUTH_TOKEN:test_auth_token}
    phone-number: ${TWILIO_PHONE_NUMBER:+1234567890}
